const fs = require('fs');
const path = require('path');

// File paths
const files = {
    layout: path.join(__dirname, 'src', 'app', 'layout.tsx'),
    page: path.join(__dirname, 'src', 'app', 'page.tsx'),
    hero: path.join(__dirname, 'src', 'components', 'Hero.tsx'),
    navbar: path.join(__dirname, 'src', 'components', 'Navbar.tsx')
};

// Replacement rules
const replacements = [
    {
        file: files.layout,
        find: 'title: "Create Next App"',
        replace: 'title: "NADOO_AI: AI News & Trends"'
    },
    {
        file: files.layout,
        find: 'description: "Generated by create next app"',
        replace: 'description: "Latest AI news, tools, and insights curated by Nadoo AI."'
    },
    {
        file: files.page,
        find: 'Data-driven real estate insights.',
        replace: 'Data-driven AI trends & insights.'
    },
    {
        file: files.page,
        find: 'Real Estate Automation',
        replace: 'AI News & Automation'
    },
    {
        file: files.page,
        find: '#Real Estate',
        replace: '#AI News'
    },
    {
        file: files.page,
        find: 'Investment',
        replace: 'Generative AI'
    },
    {
        file: files.page,
        find: 'Gwangju',
        replace: 'LLM'
    },
    {
        file: files.hero,
        find: 'Real Estate Automation',
        replace: 'Future Tech & AI'
    },
    {
        file: files.hero,
        find: '계약은 중개사가',
        replace: '비즈니스는 사람이'
    },
    {
        file: files.hero,
        find: '"NADOO_AI 에이전트"를 위한 완벽한 솔루션.',
        replace: '"AI 시대 리더"를 위한 완벽한 지식 창고.'
    },
    {
        file: files.hero,
        find: '블로그 포스팅부터 고객 관리까지',
        replace: '최신 AI 트렌드부터 실무 활용법까지'
    }
];

function updateFiles() {
    console.log('🔄 Starting Blog Pivot (Real Estate -> AI)...');

    replacements.forEach(rule => {
        try {
            if (fs.existsSync(rule.file)) {
                let content = fs.readFileSync(rule.file, 'utf8');

                // Check if already replaced
                if (content.includes(rule.replace)) {
                    console.log(`✅ Already updated: ${path.basename(rule.file)}`);
                    return;
                }

                // Replace
                const regex = new RegExp(rule.find.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
                if (regex.test(content)) {
                    content = content.replace(regex, rule.replace);
                    fs.writeFileSync(rule.file, content, 'utf8');
                    console.log(`✨ Updated: ${path.basename(rule.file)}`);
                } else {
                    console.warn(`⚠️ Warning: Could not find string "${rule.find}" in ${path.basename(rule.file)}`);
                }
            } else {
                console.error(`❌ File not found: ${rule.file}`);
            }
        } catch (err) {
            console.error(`❌ Error updating ${rule.file}:`, err.message);
        }
    });

    console.log('\n✅ Pivot Complete! Now push to GitHub to deploy.');
}

updateFiles();
